
CREATE TABLE IF NOT EXISTS tb_address (
  id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  public_email VARCHAR(100) NOT NULL,
  phone_number VARCHAR(30) NOT NULL,
  street VARCHAR(100) NOT NULL,
  city VARCHAR(50) NOT NULL,
  country VARCHAR(50) NOT NULL
);


CREATE TABLE IF NOT EXISTS tb_user (
  id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  username VARCHAR(255) NOT NULL,
  first_name VARCHAR(255),
  last_name VARCHAR(255),
  password VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  status SMALLINT DEFAULT 1,
  role SMALLINT DEFAULT 2,
  address_id INT REFERENCES tb_address(id),
  created_at TIMESTAMP,
  updated_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS tb_category (
  id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  name VARCHAR(100) NOT NULL,
  description TEXT,
  image_url VARCHAR(255),
  status SMALLINT DEFAULT 1
);


CREATE TABLE IF NOT EXISTS tb_product (
  id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  name VARCHAR(255) NOT NULL,
  price DECIMAL(5,2) NOT NULL,
  category_id INT NOT NULL REFERENCES tb_category(id),
  description TEXT,
  image_url VARCHAR(255),
  status SMALLINT DEFAULT 1,
  created_at TIMESTAMP,
  updated_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS tb_order (
  id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  user_id INT NOT NULL REFERENCES tb_user(id),
  total DECIMAL(6,2) NOT NULL,
  status SMALLINT DEFAULT 1,
  created_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS tb_order_item (
  id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  order_id INT NOT NULL REFERENCES tb_order(id),
  product_id INT NOT NULL REFERENCES tb_product(id),
  quantity INT NOT NULL
);
